import Login from "@/components/Login";
import Layout from "@/Layout/Layout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Veg Mart - The freshest of vegetables.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vegetable-icon-png-25362-Windows.ico" />
      </Head>
      <Layout>
        <>
          {/* <main>HomePage</main> */}
          <Login />
        </>
      </Layout>
    </>
  );
}
